### ISSUE TITLE
analysis: Welche Entities gehören zusammen / stehen sich nahe / Rolle der Schweiz?

### ISSUE THREAD

**Issue by buesst1** [gabrieltorresgamez/fhnw-san-project#16]
- filter by officers and entities
- projection (weighted / unweighted?) so only entities are left (edges represent same officer / weight -> the more common officers the bigger the weight)
- clustering (edge betweenness {let the GPU burn}), label propagation)
- Are there clusters where many Swiss officers are involved?

**Comment by florinbarbisch** [comment]
Close due to fast approaching deadline
